REPO_ID:  "google/paligemma-3b-pt-224"
FINETUNED_MODEL_ID: "AqsaK/paligemma_finetuned_census_data_whole"
MAX_LENGTH: 2000
WANDB_PROJECT: "paligemma"
WANDB_NAME: "paligemma_1880_whole_exp_1"
HF_DATASET: "AqsaK/HW-1880-whole-dataset"
PROMPT_TOKEN: "EXTRACT JSON."

# TRAINING CONFIGURATION
MAX_EPOCHS: 5
VAL_CHECK_INTERVAL: 0.1  # FREQUENCY OF VALIDATION CHECKS DURING AN EPOCH
CHECK_VAL_EVERY_N_EPOCH: 1
GRADIENT_CLIP_VAL: 1.0
ACCUMULATE_GRAD_BATCHES: 1
LR: 0.0001
BATCH_SIZE: 1
SEED: 2022  # UNCOMMENTED TO SET A SEED FOR REPRODUCIBILITY
NUM_NODES: 1
# WARMUP_STEPS: 50  # UNCOMMENT IF WARMUP STEPS ARE REQUIRED FOR TRAINING
RESULT_PATH: "./result"
VERBOSE: True
LIMIT_VAL_BATCHES: 0.2  # LIMIT THE NUMBER OF BATCHES FOR VALIDATION